export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api';
export const WS_BASE_URL = import.meta.env.VITE_WS_URL || 'ws://localhost:8000/ws';

export const APP_NAME = 'AI Voice Translator Pro';

export const SUPPORTED_LANGUAGES = [
  { code: 'auto', name: 'Auto Detect', flag_emoji: '🌐' },
  { code: 'en', name: 'English', flag_emoji: '🇺🇸' },
  { code: 'es', name: 'Spanish', flag_emoji: '🇪🇸' },
  { code: 'fr', name: 'French', flag_emoji: '🇫🇷' },
  { code: 'de', name: 'German', flag_emoji: '🇩🇪' },
  { code: 'it', name: 'Italian', flag_emoji: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', flag_emoji: '🇵🇹' },
  { code: 'ru', name: 'Russian', flag_emoji: '🇷🇺' },
  { code: 'zh', name: 'Chinese', flag_emoji: '🇨🇳' },
  { code: 'ja', name: 'Japanese', flag_emoji: '🇯🇵' },
  { code: 'ko', name: 'Korean', flag_emoji: '🇰🇷' },
  { code: 'ar', name: 'Arabic', flag_emoji: '🇸🇦' },
  { code: 'hi', name: 'Hindi', flag_emoji: '🇮🇳' },
  { code: 'te', name: 'Telugu', flag_emoji: '🇮🇳' },
  { code: 'ta', name: 'Tamil', flag_emoji: '🇮🇳' },
  { code: 'kn', name: 'Kannada', flag_emoji: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', flag_emoji: '🇮🇳' },
  { code: 'mr', name: 'Marathi', flag_emoji: '🇮🇳' },
  { code: 'bn', name: 'Bengali', flag_emoji: '🇧🇩' },
  { code: 'gu', name: 'Gujarati', flag_emoji: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', flag_emoji: '🇮🇳' },
  { code: 'ur', name: 'Urdu', flag_emoji: '🇵🇰' },
  { code: 'tr', name: 'Turkish', flag_emoji: '🇹🇷' },
  { code: 'nl', name: 'Dutch', flag_emoji: '🇳🇱' },
  { code: 'pl', name: 'Polish', flag_emoji: '🇵🇱' },
  { code: 'sv', name: 'Swedish', flag_emoji: '🇸🇪' },
  { code: 'no', name: 'Norwegian', flag_emoji: '🇳🇴' },
  { code: 'da', name: 'Danish', flag_emoji: '🇩🇰' },
  { code: 'fi', name: 'Finnish', flag_emoji: '🇫🇮' },
  { code: 'cs', name: 'Czech', flag_emoji: '🇨🇿' },
  { code: 'sk', name: 'Slovak', flag_emoji: '🇸🇰' },
  { code: 'ro', name: 'Romanian', flag_emoji: '🇷🇴' },
  { code: 'hu', name: 'Hungarian', flag_emoji: '🇭🇺' },
  { code: 'uk', name: 'Ukrainian', flag_emoji: '🇺🇦' },
  { code: 'bg', name: 'Bulgarian', flag_emoji: '🇧🇬' },
  { code: 'hr', name: 'Croatian', flag_emoji: '🇭🇷' },
  { code: 'sr', name: 'Serbian', flag_emoji: '🇷🇸' },
  { code: 'el', name: 'Greek', flag_emoji: '🇬🇷' },
  { code: 'he', name: 'Hebrew', flag_emoji: '🇮🇱' },
  { code: 'fa', name: 'Persian', flag_emoji: '🇮🇷' },
  { code: 'th', name: 'Thai', flag_emoji: '🇹🇭' },
  { code: 'vi', name: 'Vietnamese', flag_emoji: '🇻🇳' },
  { code: 'id', name: 'Indonesian', flag_emoji: '🇮🇩' },
  { code: 'ms', name: 'Malay', flag_emoji: '🇲🇾' },
  { code: 'sw', name: 'Swahili', flag_emoji: '🇰🇪' },
  { code: 'af', name: 'Afrikaans', flag_emoji: '🇿🇦' },
  { code: 'ca', name: 'Catalan', flag_emoji: '🏴' },
  { code: 'lt', name: 'Lithuanian', flag_emoji: '🇱🇹' },
  { code: 'lv', name: 'Latvian', flag_emoji: '🇱🇻' },
  { code: 'et', name: 'Estonian', flag_emoji: '🇪🇪' },
];

export const THEME_COLORS = {
  primary: '#3b82f6',
  success: '#10b981',
  danger: '#ef4444',
  warning: '#f59e0b',
};
